//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqliteTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Id
    {
        public long Id1 { get; set; }
        public long Value { get; set; }
    }
}
